### PR TITLE
Update angular to v15 and fix upcomming errors

### PR DESCRIPTION
**Pull request by tom-wegener**
I just updated angular to v15 and replaced some things which were deprecated or legacy-components.

### CODE REVIEW

**Comment by tom-wegener** [comment]
Thanks for your small tutorial, it helped a bunch but it was a bit outdated so I tried to update this project first and then implement it into my own. And since I already updated this project, I thought I could contribute that work to the original.

**Comment by thisiszoaib** [comment]
Thanks Tom, let me check it out and get back to you :)

**Comment by thisiszoaib** [comment]
@tom-wegener The update has also messed with the layout quite a bit. So if you can get it to be like it was before, I'll be happy to merge. Otherwise, will have to pass.

**Comment by tom-wegener** [comment]
Hey, I updated it to use native css flexbox instead of the angular grid, so it should be fine now.

**Pull request closed without merging**
